#---------------------------General Params-------------------------------------#


case : "gridfill_avrm_fe"
# filename : 'input_data/blobs_distribution_006750.csv'
# filename : 'input_data/blobs_distribution_002250.csv'
# filename : 'input_data/blobs_distribution_022500.csv'
filename : 'input_data/blobs_distribution_015750.csv'

data_folder : 'data_1'
plots_folder : 'plots_1'

#--------------------------Time Params--------------------------------------#
nTimeSteps : 100    #number of lagrangian time-steps
writeInterval_plots : 5
compression_stride : 20  # number of timesteps between compressions
T0 : 0 # starting timestep

deltaTc : 0.02      #lagrangian, convection time-step

#---------------------------Lagrangian Params-------------------------------------#

xMin : [-0.5]         #minimum x for initial blobs
xMax : [0.5]          #maximum x for initial blobs
yMin : [-0.5]         #minimum y for initial blobs
yMax : [0.5]          #maximum y for initial blobs

vInfx : 10.0           #freestream velocity in x direction
vInfy : 0.0           #freestream velocity in y direction
core : 0.01       #size of all starting particles
overlap : 1.



nu : 0.001
gammaC : 1.0

  #Computation Params
hardware : "gpu"
# hardware : 'gpu'
method : "direct"

  #Blob Control Params
method_popControl : 'implicit'
stepRedistribution : 0
stepPopulationControl : 1
gThresholdLocal : 1e-12
gThresholdGlobal : 1e-12
blobsRedistribute : 'all'

  #Blob Diffusion Params
method_diffusion : 'adaptive_vrm'

  #Time integration Params
time_integration_method : 'euler'

  #Kernel params
kernel : 'gauss'
coreSize : 'variable'

  #xShift,yShift
xShift : 0.0
yShift : 0.0

#--------------------------- Compression Params -------------------------------------#


compression_method : 'gridfill'
compression_params : {'Csigma' : 1., 'margin' : 0.25}

support_method : 'patch'
support_params : {'radius' : 1.5, 'size_bound' : 500, 'x_bound': 10., 'sort' : True}

compression_func_values: {'x0' : 10, 'y0' : 0.95, 'x1' : 100, 'y1' : 0.1}

#---------------------------Plot Params-------------------------------------#
nPlotPoints : 100    #plot points in each direction
xMinPlot : 10.      #minimum x to plot
xMaxPlot : 70.       #maximum x to plot
yMinPlot : -2.0       #minimum y to plot
yMaxPlot : 2.0        #maximum y to plot

# run_analytical_flag : True
plot_flag : True

